// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH inserted_feed_follow AS (
	INSERT INTO feed_follows (
		id,
		created_at,
		updated_at,
		user_id,
		feed_id
	) VALUES (
		$1,
		$2,
		$3,
		$4,
		$5
	) RETURNING id, created_at, updated_at, user_id, feed_id
)
SELECT 
	inserted_feed_follow.id, inserted_feed_follow.created_at, inserted_feed_follow.updated_at, inserted_feed_follow.user_id, inserted_feed_follow.feed_id,
	feeds.name as feed_name,
	users.name as user_name
FROM inserted_feed_follow
INNER JOIN users
	ON inserted_feed_follow.user_id = users.id
INNER JOIN feeds
	ON inserted_feed_follow.feed_id = feeds.id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	FeedName  string
	UserName  string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.FeedName,
		&i.UserName,
	)
	return i, err
}

const getFollowedFeeds = `-- name: GetFollowedFeeds :many
SELECT feeds.name as feed_name, feeds.url as feed_url, users.name as user_name
FROM feed_follows
INNER JOIN users
        ON user_id = users.id
INNER JOIN feeds
        ON feed_id = feeds.id
WHERE users.name = $1
`

type GetFollowedFeedsRow struct {
	FeedName string
	FeedUrl  string
	UserName string
}

func (q *Queries) GetFollowedFeeds(ctx context.Context, name string) ([]GetFollowedFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowedFeeds, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowedFeedsRow
	for rows.Next() {
		var i GetFollowedFeedsRow
		if err := rows.Scan(&i.FeedName, &i.FeedUrl, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
